[package]
name = "CoinPool"
version = "0.1.0"

[dependencies]
AptosFramework = { local = "../meta/aptos/aptos-core/aptos-move/framework/aptos-framework" }

[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
coin_pool = "_"

[dev-addresses]
coin_pool = "0x11"
